[colors]

[colors.normal]
black   = "#1a2424"
red     = "#e6441a"
green   = "#1a6b6e"
yellow  = "#e68040"
blue    = "#2a7a80"
magenta = "#c4753d"
cyan    = "#40b8b4"
white   = "#d8d0c8"

[colors.bright]
black   = "#4d6b6b"
red     = "#e66b40"
green   = "#40c4c0"
yellow  = "#e6a052"
blue    = "#52c9cd"
magenta = "#e6b375"
cyan    = "#70e0dd"
white   = "#f0e8e0"

[colors.cursor]
cursor = '#e66a4d'   # Slightly muted sun orange
text = '#1a1a1a'     # Lighter dark text

[colors.primary]
background = '#0f0f0f'
foreground = '#e0d8d0'

[colors.selection]
background = '#4d5a5a' # Slightly darker selection
text = '#d0c8c0'     # Slightly darker text
