[colors]

[colors.normal]
black   = "#0f1a1a"
red     = "#ff4d1a"
green   = "#1a7578"
yellow  = "#ff8f40"
blue    = "#2a858c"
magenta = "#d4803d"
cyan    = "#40c4c0"
white   = "#e8ddd5"

[colors.bright]
black   = "#4d7575"
red     = "#ff7540"
green   = "#40d4d0"
yellow  = "#ffad52"
blue    = "#52d9dd"
magenta = "#ffc275"
cyan    = "#70f0ed"
white   = "#fff8f0"

[colors.cursor]
cursor = '#f47a4d'   # Vibrant sun orange for high visibility
text = '#0c0c0c'     # The darkest silhouette color for text

[colors.primary]
background = '#040404'
foreground = '#f5f0e8'

[colors.selection]
background = '#4d6161' # A mid-tone teal from the sky
text = '#e0d8d0'     # Bright but soft off-white text
